export const ADD_TODAY_TASK = "ADD_TODAY_TASK";
export const COMPLETE_TODAY_TASK = "COMPLETE_TODAY_TASK";
export const LOAD_TODAY_TASKS = "LOAD_TODAY_TASKS";
export const CHANGE_PERCENT_TODAY = "CHANGE_PERCENT_TODAY";